#!/bin/sh

echo "Removing SC Search plugin..."
rm -rf "/usr/lib/enigma2/python/Plugins/Extensions/scsearch"
rm -rf "/usr/lib64/enigma2/python/Plugins/Extensions/scsearch"
rm -f /tmp/scsearch-use-lib64
rm -f /tmp/scLog.txt
rm -f /home/root/logs/scLog.txt

exit 0
